name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# self contained tests
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true" # Fetch submodules
      - name: Spin-up services
        run: docker compose --profile ci up -d
      - name: Install dependencies
        run: docker exec -t publisher-ci bun install
      - name: Build code
        run: docker exec -t publisher-ci bun run build
      - name: Run tests
        run: docker exec -t publisher-ci sh -c "cd packages/server && bun test ./src/service/model.spec.ts ./src/service/package.spec.ts ./src/__tests__/setup.spec.ts ./src/__tests__/mcp_execute_query_tool.integration.spec.ts ./src/__tests__/mcp_resource.integration.spec.ts ./src/__tests__/mcp_transport.integration.spec.ts"
